# Задания практической работы
## Задание 1. Создание и изменение массивов
Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [295]:
import numpy as np

In [297]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [299]:
arr=arr*2
arr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [301]:
arr[arr>10]=0
arr

array([[ 2,  4,  6],
       [ 8, 10,  0],
       [ 0,  0,  0]])

## Задание 2. Работа с булевыми масками
Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.

In [227]:
arr=np.random.randint(1,101,size=20)
print(arr)

[58 84 52 92 53 29 62 25 39 41  6  4 99  7 75 71 61 65 50 41]


In [229]:
print(arr[arr%5==0])

[25 75 65 50]


In [231]:
arr[arr%5==0]=-1
print(arr)

[58 84 52 92 53 29 62 -1 39 41  6  4 99  7 -1 71 61 -1 -1 41]


## Задание 3. Объединение и разбиение массивов
Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50.

- Объедините эти массивы в один двумерный массив (по строкам).
- Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

Выведите все промежуточные и итоговые результаты.

In [235]:
a=np.random.randint(1,50,size=(1,5))
b=np.random.randint(1,50,size=(1,5))
print(a,'\n')
print(b)

[[49  1 40 46  3]] 

[[25 44 33 15  5]]


In [237]:
c=np.concatenate((a,b),axis=0)
print(c)

[[49  1 40 46  3]
 [25 44 33 15  5]]


In [239]:
list(zip((c)))

[(array([49,  1, 40, 46,  3]),), (array([25, 44, 33, 15,  5]),)]

## Задание 4. Генерация и работа с линейными последовательностями
Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [242]:
arr = np.linspace(-10, 10, 50)
print(arr)

[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]


In [244]:
np.sum(arr)

7.105427357601002e-15

In [246]:
print(np.sum(arr[arr>0]))
print(np.sum(arr[arr<0]))

127.55102040816328
-127.55102040816327


## Задание 5. Работа с диагональными и единичными матрицами
Создайте:

- Единичную матрицу размером 4×4.
- Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы).
                                                                                
Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [249]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [251]:
b=np.matrix('5 0 0 0;0 10 0 0; 0 0 15 0; 0 0 0 20')
b=np.array(b)
b

array([[ 5,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0, 15,  0],
       [ 0,  0,  0, 20]])

In [253]:
a_s=np.sum(a)
b_s=np.sum(b)
print(a_s>b_s,a_s<b_s,a_s==b_s)

False True False


## Задание 6. Создание и базовые операции с матрицами
Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:

- Их сумму
- Их разность
- Их поэлементное произведение

In [256]:
a=np.random.randint(1,20,size=(3,3))
b=np.random.randint(1,20,size=(3,3))

In [258]:
print((a+b),'\n\n',(a-b),'\n\n',(a*b))

[[31 11 17]
 [15 31 11]
 [14 15 12]] 

 [[-5 -9 15]
 [ 1  1  1]
 [-2 -1 -6]] 

 [[234  10  16]
 [ 56 240  30]
 [ 48  56  27]]


## Задание 7. Умножение матриц
Создайте две матрицы NumPy:

- Первую размером 2×3, заполненную случайными числами от 1 до 10.
- Вторую размером 3×2, заполненную случайными числами от 1 до 10.

Выполните матричное умножение (@ или np.dot) и выведите результат.

In [265]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(1,10,size=(3,2))
print(np.dot(a,b))

[[36 15]
 [78 30]]


## Задание 8. Определитель и обратная матрица
Создайте случайную квадратную матрицу 3×3. Найдите и выведите:

- Определитель этой матрицы
- Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена) 

Используйте функции np.linalg.det и np.linalg.inv

In [268]:
a=np.random.randint(1,100,size=(3,3))

In [270]:
print(np.linalg.det(a))

-28779.000000000036


In [274]:
if np.linalg.det(a):
    print(np.linalg.inv(a))
else:
    print("Матрица вырождена")

[[-0.04402516 -0.03926474  0.06164217]
 [ 0.01257862  0.03568574 -0.03655443]
 [ 0.11320755  0.05597832 -0.09142083]]


## Задание 9. Транспонирование и след матрицы
Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:

- Исходную матрицу
- Транспонированную матрицу
- След матрицы (сумму элементов на главной диагонали)

Используйте np.trace для нахождения следа.

In [277]:
a=np.random.randint(1,50,size=(4,4))

In [279]:
print(a)

[[10  1  6 20]
 [29 26 21 10]
 [29 21 20  9]
 [39 29 13 21]]


In [281]:
print(a.T)

[[10 29 29 39]
 [ 1 26 21 29]
 [ 6 21 20 13]
 [20 10  9 21]]


In [283]:
print(np.sum(np.diag(a)))

77


## Задание 10. Системы линейных уравнений
Решите систему линейных уравнений вида:

$$
\begin{cases}
2x + 3y - z = 5 \\
4x - y + 2z = 6 \\
-3x + 5y + 4z = -2
\end{cases}
$$

Используйте матричное представление $Ax = B$, где $A$ — матрица коэффициентов, $x$ — вектор неизвестных, $B$ — вектор правой части. Решите систему с помощью `np.linalg.solve` и выведите результат.


In [330]:
A=np.matrix('2 3 -1;4 -1 2;-3 5 4')
A=np.array(A)
A

array([[ 2,  3, -1],
       [ 4, -1,  2],
       [-3,  5,  4]])

In [290]:
B = np.array([5, 6, -2])

In [292]:
sol = np.linalg.solve(A, B)
print(sol)

[1.63963964 0.57657658 0.00900901]


## Задание 11. Индивидуальное задание
### Вариант 22
**Распределение товара по складам**. Магазин получил 600 коробок с товаром, которые нужно распределить по трем складам. На второй склад должно быть отправлено на 50 коробок больше, чем на первый, а на третий склад — в два раза больше, чем на второй. Сколько коробок отправят на каждый склад?

In [348]:
import numpy as np

A = np.array([
    [1, 1, 2],  # 1x + 1(x+50) + 2(x+50)
    [0, 1, 0],  # На второй склад на 50 больше, чем на первый
    [0, 0, 2]   # На третий склад в два раза больше, чем на второй
])

B = np.array([600, 50, 50])

# numpy
solution = np.linalg.solve(A, B)
print("Решение методом np.linalg.solve:")
print(f"x = {solution[0]}, второй склад = {solution[1] + 50}, третий склад = {2 * (solution[1] + 50)}")

# метод Крамера
det_A = np.linalg.det(A)

A_x = A.copy()
A_x[:, 0] = B
det_Ax = np.linalg.det(A_x)
x = det_Ax / det_A

A_y = A.copy()
A_y[:, 1] = B
det_Ay = np.linalg.det(A_y)
y = det_Ay / det_A

A_z = A.copy()
A_z[:, 2] = B
det_Az = np.linalg.det(A_z)
z = det_Az / det_A

print("\nРешение методом Крамера:")
print(f"x = {x}, второй склад = {y + 50}, третий склад = {2 * (y + 50)}")

# Матричный метод
A_inv = np.linalg.inv(A)
solution_matrix = np.dot(A_inv, B)
print("\nРешение матричным методом:")
print(f"x = {round(solution_matrix[0])}, второй склад = {round(solution_matrix[1] + 50)}, третий склад = {round(2 * (solution_matrix[1] + 50))}")


Решение методом np.linalg.solve:
x = 500.0, второй склад = 100.0, третий склад = 200.0

Решение методом Крамера:
x = 499.9999999999999, второй склад = 99.99999999999997, третий склад = 199.99999999999994

Решение матричным методом:
x = 500, второй склад = 100, третий склад = 200
