In [3]:
import numpy as np
m=np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)
print(type(m))

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]
<class 'numpy.matrix'>


In [5]:
m=np.array(m)
type(m)

numpy.ndarray

In [7]:
m.shape

(3, 4)

In [9]:
m.max()

9

In [11]:
np.max(m)

9

In [13]:
print(m.max(axis=1))
print(m.max(axis=0))

[4 8 9]
[9 6 7 8]


In [15]:
print(m.mean())
print(m.mean(axis=1))
print(m.sum())
print(m.sum(axis=0))

4.833333333333333
[2.5 6.5 5.5]
58
[15  9 15 19]


In [17]:
nums=np.array([1,2,3,4,5,6,7,8,9,10])
letters=np.array(['a','b','c','d','a','e','b'])

In [19]:
less_then_5=nums<5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [21]:
pos_a=letters=='a'
pos_a

array([ True, False, False, False,  True, False, False])

In [23]:
nums[less_then_5]

array([1, 2, 3, 4])

In [25]:
mod_m=np.logical_and(m>=3,m<=7)
mod_m

array([[False, False,  True,  True],
       [ True,  True,  True, False],
       [False, False,  True,  True]])

In [27]:
m[mod_m]

array([3, 4, 5, 6, 7, 5, 7])

In [29]:
nums=np.array([1,2,3,4,5,6,7,8,9,10])
nums[nums<5]

array([1, 2, 3, 4])

In [31]:
nums[nums<5]=10
print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [33]:
m[m>7]=25
print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]


In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(5,12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [39]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [41]:
a=[[1,2],[3,4]]
np.matrix(a)

matrix([[1, 2],
        [3, 4]])

In [43]:
b=np.array([[5,6],[7,8]])
np.matrix(b)

matrix([[5, 6],
        [7, 8]])

In [45]:
np.matrix('[1, 2; 3, 4]')

matrix([[1, 2],
        [3, 4]])

In [47]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.ravel(A)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.ravel(A, order='C')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.ravel(A, order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [61]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(a % 2 == 0, a * 10, a / 10)

array([ 0. ,  0.1, 20. ,  0.3, 40. ,  0.5, 60. ,  0.7, 80. ,  0.9])